# Generated by Django 6.0.6 on 2026-06-21 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='posts_gustados', to=settings.AUTH_USER_MODEL),
        ),
    ]
