# Generated by Django 6.0.6 on 2026-07-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_publicacion_imagen_publicacion_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('publicacion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veces_compartida', to='app1.publicacion')),
                ('usuario_que_comparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
