# Generated by Django 6.0.6 on 2026-07-03 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_conexion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
